export const fields = [
  "Tên sản phẩm(*)",
  "Mã BARCODE",
  "Theo dõi kho (Có/Không)",
  "Vị trí kệ hàng",
  "Danh mục",
  "Thuộc tính",
  "Thuộc tính tìm kiếm",
  "Cân nặng(g)",
  "Hoa hồng CTV (%/VND)",
  "Xu cho đại lý",
  "Mô tả",
  "Nội dung cho CTV",
  "Trạng thái (Ẩn/Hiện)",
  "Tiêu đề SEO",
  "Miêu tả SEO",
  "Phân loại(Có/Không)(*)",
  "Phân loại chính",
  "Phân loại phụ",
  "DS phân loại",
  "Giá bán lẻ",
  "Giá nhập",
  "Mã SKU(*)",
  "Hình ảnh",
];
